#!/usr/bin/env bash
# Configures Nginx redirection

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get -y install nginx
fi

# Create a configuration file for the redirection
REDIRECT_CONFIG="/etc/nginx/sites-available/redirect_me"
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > "$REDIRECT_CONFIG"

# Enable the configuration by creating a symbolic link
ln -s "$REDIRECT_CONFIG" "/etc/nginx/sites-enabled/"

# Restart Nginx to apply the changes
service nginx restart
