#!/usr/bin/env bash
# Fix Nginx listening on port 80
# Change to the sites-enabled folder for Nginx
cd /etc/nginx/sites-enabled/ || exit;
# Delete the default configuration file
rm default;
# Create a symbolic link to the default configuration file in sites-available
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx to apply the changes
service nginx restart
