#!/usr/bin/env bash
# Set Nginx to listen on port 80
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
# Restart Nginx to apply the changes
sudo service nginx restart
# Kill the Nginx process using the PID from /var/run/nginx.pid
kill -9 "$(cat /var/run/nginx.pid)"
