#!/usr/bin/env bash

# This script creates an RSA key pair with the name `school` and 4096 bits.
# The key is protected by the passphrase `betty`.

ssh-keygen -t rsa -b 4096 -C "school" -f school -P "betty"

